apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-servicemonitor
  namespace: fastapi
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: fastapi
  namespaceSelector:
    matchNames:
      - fastapi
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
