apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress-resource
  namespace: fastapi
spec:
  ingressClassName: nginx
  rules:
  - host: {INGRESS_ADDRESS}
    http:
      paths:
      - path: /healthz
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      - path: /work
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      - path: /random
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      
