name: fastapi-infra-destroy

on:
  workflow_dispatch

jobs:
  Destroy-Infra:
    name: Deploy-Infra
    permissions:
     id-token: write #required for github-aws oidc authentication
     contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Terraform Plugins cache folder
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Enable Terraform Plugin Cache
        run: echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV #tell Terraform where to store and load provider plugins

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      
      - name: Setup Hashicorp Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.3"
      
      - name: Update the KubeConfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
#
#      - name: Terraform Init, Destory for Loki-setup
#        working-directory: ./terraform/cluster/loki-setup
#        run: |
#          terraform init
#          terraform destroy -auto-approve
#      
      - name: Terraform Init, Destory EKS Resources
        working-directory: ./terraform/cluster/eks
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Terraform Init, Destroy Global Resources
        working-directory: ./terraform/global
        run: |
          terraform init
          terraform destroy -auto-approve


      
   
    



